name: "Ruby on Rails CI"
on:
  push:
    branches: [ "*" ]
jobs:
  build_and_run_tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        # Set health checks to wait until mysql has started
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.2.0
          security-enabled: false

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests with sqlite3
        env:
          RAILS_ENV: test
          DATABASE_URL: sqlite3:db/test.sqlite3
          SELENIUM_SERVER: 127.0.0.1
        run: |
          bundle exec rails db:reset
          bundle exec rails test --verbose
          #bundle exec rails test:system
      - name: Run tests with mysql
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://test:test@127.0.0.1:3306/test
          SELENIUM_SERVER: 127.0.0.1
        run: |
          bundle exec rails db:reset
          bundle exec rails test --verbose
          #bundle exec rails test:system
